// src/components/greeting.tsx
export function Greeting({
  name,
  message = 'Continue where you left off',
}: {
  name: string;
  message?: string;
}) {
  return (
    <div className="text-center">
      <h1 className="text-3xl font-semibold text-foreground">Good morning, {name}</h1>
      <p className="mt-2 text-muted-foreground">{message}</p>
    </div>
  );
}

// src/lib/components/greeting/greeting.svelte
<script lang="ts">
  let {
    name,
    message = 'Continue where you left off',
  }: {
    name: string;
    message?: string;
  } = $props();
</script>

<div class="text-center">
  <h1 class="text-3xl font-semibold text-foreground">Good morning, {name}</h1>
  <p class="mt-2 text-muted-foreground">{message}</p>
</div>
