// src/components/sidebar-item.tsx
import { cn } from "#/lib/utils";
import type { LucideIcon } from "lucide-react";
import { Link } from "@tanstack/react-router";

export function SidebarItem({
  label,
  href,
  selected,
  icon: Icon,
}: {
  label: string;
  href: string;
  selected?: boolean;
  icon?: LucideIcon;
}) {
  return (
    <li
      className={cn(
        "w-full py-2 px-3 border-none bg-transparent text-gray-500 font-normal text-sm rounded-md hover:text-black hover:bg-white hover:font-medium flex items-center gap-2 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        selected && "text-black bg-white font-medium",
      )}
    >
      {Icon ? <Icon /> : null}
      <Link to={href}> {label}</Link>
    </li>
  );
}

// src/lib/components/sidebar/sidebar-item.svelte
<script lang="ts">
  import clsx from 'clsx';
  import { twMerge } from 'tailwind-merge';
  import type { LucideIcon } from '@lucide/svelte';

  interface SidebarItemProps {
    label: string;
    href: string;
    selected?: boolean;
    icon?: LucideIcon;
  }

  let { label, href, selected, icon: Icon }: SidebarItemProps = $props();
</script>

<li
  class={twMerge(
    clsx(
      "w-full py-2 px-3 border-none bg-transparent text-gray-500 font-normal text-sm rounded-md hover:text-black hover:bg-white hover:font-medium flex items-center gap-2 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
      selected && 'text-black bg-white font-medium',
    ),
  )}
>
  <Icon />
  <a {href}> {label} </a>
</li>
