// src/components/novel/novel-card.tsx
import { Badge, Card, Group, Stack, Text, Title } from "@mantine/core";
import { Link } from "@tanstack/react-router";
import { formatDistanceToNow } from "date-fns";
import { STATUS_ACTION_VERBS, STATUS_BADGE_COLORS } from "#/lib/novels/status-metadata";
import type { NovelSummary } from "#/lib/translator/service";
import {
  sourceLanguageLabel,
  type NovelStatus,
  type SourceLanguage,
} from "#/lib/novels/novels-core";

export function NovelCard({ novel }: { novel: NovelSummary }) {
  const badgeColor = STATUS_BADGE_COLORS[novel.status as NovelStatus];
  const parsedAt = formatDistanceToNow(novel.updated_at, { addSuffix: true });

  return (
    <Card
      withBorder
      className="p-4 hover:border-black cursor-pointer focus:outline-ring focus-visible:outline-2 focus-visible:outline-ring"
      renderRoot={(props) => <Link to="/novels/$slug" params={{ slug: novel.slug }} {...props} />}
    >
      <Stack className="gap-4">
        <Stack className="gap-1">
          <Title order={3} className="text-base font-medium line-clamp-2">
            {novel.name}
          </Title>
          <Text className="text-xs">
            {sourceLanguageLabel(novel.source_language as SourceLanguage)} -&gt; English
          </Text>
        </Stack>
        <Group className="items-center justify-between">
          <Badge variant={badgeColor ? "light" : "default"} color={badgeColor} size="xs">
            {novel.status}
          </Badge>
          <Text className="text-xs font-medium">
            {novel.status === "needs review"
              ? `${novel.parsed_chapters}/${novel.total_chapters} chapters`
              : `${novel.total_chapters} chapters`}
          </Text>
        </Group>

        <Text c="dimmed" className="text-xs font-medium line-clamp-1">
          {novel.status === "failed"
            ? (novel.last_error ?? `Failed ${parsedAt}`)
            : `${STATUS_ACTION_VERBS[novel.status as NovelStatus]} ${parsedAt}`}
        </Text>
      </Stack>
    </Card>
  );
}

// src/lib/components/novel-card/novel-card.svelte
<script lang="ts">
interface Novel {
  id: number;
  title: string;
  languagePair: string;
  progress: number;
  totalChapters: number;
  currentChapter: number;
  lastUpdated: string;
  initial: string;
}

let { novel }: { novel: Novel } = $props();
</script>

<article class="border rounded-md border-border p-4 hover:bg-card hover:border-black transition-colors cursor-pointer focus:outline-ring focus-visible:outline-2 focus-visible:outline-ring">
  <div class="flex items-start gap-3">
    <div class="flex-1 min-w-0">
      <h3 class="text-lg font-medium text-foreground line-clamp-2">
        {novel.title}
      </h3>
      <p class="mt-1 text-sm text-muted-foreground line-clamp-1">
        {novel.languagePair}
      </p>
    </div>
  </div>

  <div class="mt-3 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <span class="text-xs text-muted-foreground">Active</span>
    </div>
    <div class="text-right">
      <p class="text-sm font-medium text-foreground">
        {novel.currentChapter} / {novel.totalChapters} chapters
      </p>
      <p class="text-xs text-muted-foreground">{novel.lastUpdated}</p>
    </div>
  </div>
</article>
