// src/lib/components/credits-badge/credits-badge.svelte
<script lang="ts">
  import Coins from '@lucide/svelte/icons/coins';
  import Badge from '../ui/badge/badge.svelte';
  import Skeleton from '../ui/skeleton/skeleton.svelte';

  type Props = { loading: true } | { credits: string } | { error: string };

  let props: Props = $props();
  const isDestructive = $derived('error' in props);
  const formattedCredits = $derived(
    'credits' in props ? `${Number(props.credits).toFixed(2)}` : '0',
  );
</script>

<Badge color={isDestructive ? 'destructive' : undefined}>
  <Coins />
  {#if 'loading' in props}
    <Skeleton class="h-5 w-20" />
  {:else if 'error' in props}
    {props.error}
  {:else}
    {formattedCredits} Credits
  {/if}
</Badge>

// src/components/credits-badge.tsx
import { Coins } from 'lucide-react';
import { Badge } from './ui/badge';
import { Skeleton } from './ui/skeleton';

type CreditsProps =
  | { status: 'loading' }
  | { status: 'error'; error: string }
  | { status: 'success'; credits: string };

export function CreditsBadge(props: CreditsProps) {
  const isDestructive = props.status === 'error';
  const formattedCredits =
    props.status === 'success'
      ? `${Number(props.credits).toFixed(2)}`
      : '0';

  return (
    <Badge color={isDestructive ? 'destructive' : undefined}>
      <Coins />
      {props.status === 'loading' ? (
        <Skeleton className="h-5 w-20" />
      ) : props.status === 'error' ? (
        props.error
      ) : (
        `${formattedCredits} Credits`
      )}
    </Badge>
  );
}
