// src/lib/components/Header.svelte
<script>
  import { Coins, RotateCcw } from '@lucide/svelte';
</script>

<header class="fixed bg-gray-100 border-b border-gray-300 w-full">
  <nav aria-label="main navigation" class="p-4 flex items-baseline">
    <div class="flex items-baseline gap-6">
      <a href="/" class="text-2xl font-semibold leading-none"> Translator</a>

      <ul class="flex items-baseline">
        <li>
          <a href="/projects" class="text-lg font-light leading-none"> Projects</a>
        </li>
      </ul>
    </div>

    <span
      class="ml-auto border border-gray-300 rounded-md flex items-stretch bg-white"
      aria-label="120 credits remaining"
    >
      <span class="py-1.5 px-3 flex items-center text-sm">
        <Coins size={18} />
        <span class="ml-2">100 credits</span>
      </span>
      <button
        type="button"
        class="border-l border-gray-300 py-1.5 px-3 cursor-pointer flex items-center"
        aria-label="Refresh credits"
      >
        <span aria-hidden="true" class="flex items-center">
          <RotateCcw size={16} />
        </span>
      </button>
    </span>
  </nav>
</header>

// src/components/header.tsx
import { useEffect, useState } from 'react';
import { getCredits } from '#/lib/credits';
import { getErrorMessage } from '#/lib/utils';
import { CreditsBadge } from './credits-badge';

type CreditsState =
  | { status: 'loading' }
  | { status: 'error'; error: string }
  | { status: 'success'; credits: string };

export function Header() {
  const [credits, setCredits] = useState<CreditsState>({ status: 'loading' });

  useEffect(() => {
    let cancelled = false;
    getCredits()
      .then((balance) => {
        if (!cancelled) setCredits({ status: 'success', credits: balance });
      })
      .catch((error: unknown) => {
        if (!cancelled) setCredits({ status: 'error', error: getErrorMessage(error) });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <header className="fixed z-10 top-0 left-0 bg-gray-100 border-b border-gray-300 py-4 w-full">
      <nav aria-label="main navigation" className="mx-auto px-6 max-w-5xl flex items-baseline">
        <div className="flex items-baseline gap-6">
          <a href="/" className="text-2xl font-normal leading-none">
            {' '}
            Translator
          </a>
        </div>

        <div className="ml-auto max-w-70 flex gap-4 justify-between items-center">
          <CreditsBadge {...credits} />
        </div>
      </nav>
    </header>
  );
}
