// src/lib/components/ui/skeleton/skeleton.svelte
<script lang="ts">
  import type { SvelteHTMLElements } from 'svelte/elements';

  import { cn } from '$lib/utils.js';

  let { class: className, ...restProps }: SvelteHTMLElements['div'] = $props();
</script>

<div
  aria-hidden="true"
  class={cn('rounded-md bg-gray-300 animate-pulse', className)}
  {...restProps}
></div>

// src/components/ui/skeleton.tsx
import type { HTMLAttributes } from "react";
import { cn } from "#/lib/utils";

export function Skeleton({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      aria-hidden="true"
      className={cn("rounded-md bg-gray-300 animate-pulse", className)}
      {...props}
    />
  );
}
